fix(terraform1): fixed the pr commenter erroragianai

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -11,7 +11,90 @@ permissions:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  TF_WORKSPACE: "example"
+  TF_VERSION: "1.4.6"
+
 jobs:
+  terraform:
+    name: Run Terraform and Comment
+    runs-on: ubuntu-latest
+    steps:
+      - name: HashiCorp - Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: ${{ env.TF_VERSION }}
+
+      - name: Terraform Format
+        id: fmt
+        run: |
+          terraform fmt -check -recursive -diff
+        continue-on-error: true
+
+      - name: Post Format Comment
+        if: ${{ always() && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure') }}
+        uses: GetTerminus/terraform-pr-commenter@v3
+        with:
+          commenter_type: fmt
+          commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
+          commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
+
+      - name: Terraform Init
+        id: init
+        run: terraform init -lock=false -input=false
+
+      - name: Post Init Comment
+        if: ${{ always() && (steps.init.outcome == 'success' || steps.init.outcome == 'failure') }}
+        uses: GetTerminus/terraform-pr-commenter@v3
+        with:
+          commenter_type: init
+          commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
+          commenter_exitcode: ${{ steps.init.outputs.exitcode }}
+
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate
+
+      - name: Post TF Validate Comment
+        if: ${{ always() && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure') }}
+        uses: GetTerminus/terraform-pr-commenter@v3
+        with:
+          commenter_type: validate
+          commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
+          commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
+
+      - name: TFLint - Setup
+        id: tflint
+        uses: terraform-linters/setup-tflint@v3
+        with:
+          tflint_wrapper_enabled: true
+
+      - name: TFLint - Run
+        run: |
+          tflint --version
+          tflint --init
+          tflint
+
+      - name: Post TFLint Comment
+        if: ${{ always() && (steps.tflint.outcome == 'success' || steps.tflint.outcome == 'failure') }}
+        uses: GetTerminus/terraform-pr-commenter@dpr-update-commenter
+        with:
+          commenter_type: tflint
+          commenter_input: ${{ format('{0}{1}', steps.tflint.outputs.stdout, steps.tflint.outputs.stderr) }}
+          commenter_exitcode: ${{ steps.tflint.outputs.exitcode }}
+
+      - name: Terraform Plan
+        id: plan
+        run: terraform plan -lock=false -input=false |& tee tf_plan.txt
+
+      - uses: GetTerminus/terraform-pr-commenter@v3
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TF_WORKSPACE: ${{ inputs.terraform_workspace }}
+        with:
+          commenter_type: plan
+          commenter_plan_path: tf_plan.txt
+          commenter_exitcode: ${{ steps.plan.outputs.exit }}
+
   filter:
     runs-on: ubuntu-latest
     outputs:
@@ -29,8 +112,10 @@ jobs:
               - 'terraform1/**'
             terraform2:
               - 'terraform2/**'
-            
 
+
+    
+  
   # terraform2_lint:
   #   needs: filter
   #   runs-on: ubuntu-latest
@@ -180,208 +265,208 @@ jobs:
   #       with:
   #         comment: true
   
-  terraform1_lint:
-    needs: filter
-    runs-on: ubuntu-latest
-    if: needs.filter.outputs.terraform1_changed == 'true'
-    steps:
-      - uses: actions/checkout@v3
+  # terraform1_lint:
+  #   needs: filter
+  #   runs-on: ubuntu-latest
+  #   if: needs.filter.outputs.terraform1_changed == 'true'
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.12.2
-      - name: TFLint - Setup
-        uses: terraform-linters/setup-tflint@v3
-        with:
-          tflint_wrapper_enabled: true
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.12.2
+  #     - name: TFLint - Setup
+  #       uses: terraform-linters/setup-tflint@v3
+  #       with:
+  #         tflint_wrapper_enabled: true
 
-      - name: TFLint - Run
-        id: tflint-run
-        run: |
-          set -o pipefail
-          tflint --init
-          tflint | tee result.log
-        continue-on-error: true
+  #     - name: TFLint - Run
+  #       id: tflint-run
+  #       run: |
+  #         set -o pipefail
+  #         tflint --init
+  #         tflint | tee result.log
+  #       continue-on-error: true
 
-      - name: Capture TFLint output and exit code
-        id: tflint-output
-        run: |
-          echo "output<<EOF" >> $GITHUB_OUTPUT
-          cat result.log >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          echo "exitcode=$?" >> $GITHUB_OUTPUT
+  #     - name: Capture TFLint output and exit code
+  #       id: tflint-output
+  #       run: |
+  #         echo "output<<EOF" >> $GITHUB_OUTPUT
+  #         cat result.log >> $GITHUB_OUTPUT
+  #         echo "EOF" >> $GITHUB_OUTPUT
+  #         echo "exitcode=$?" >> $GITHUB_OUTPUT
 
-      - name: Post TFLint Comment
-        if: always()
-        uses: GetTerminus/terraform-pr-commenter@dpr-update-commenter
-        with:
-          commenter_type: tflint
-          commenter_input: ${{ steps.tflint-output.outputs.output }}
-          commenter_exitcode: ${{ steps.tflint-output.outputs.exitcode }}
-
-
-      # - name: TFLint - Setup
-      #   id: tflint
-      #   uses: terraform-linters/setup-tflint@v3
-      #   with:
-      #     tflint_wrapper_enabled: true
-      # - name: TFLint - Run
-      #   run: |
-      #     tflint --version
-      #     tflint --init
-      #     tflint
-      # - name: Post TFLint Comment
-      #   if: ${{ always() && (steps.tflint.outcome == 'success' || steps.tflint.outcome == 'failure') }}
-      #   uses: GetTerminus/terraform-pr-commenter@dpr-update-commenter
-      #   with:
-      #     commenter_type: tflint
-      #     commenter_input: ${{ format('{0}{1}', steps.tflint.outputs.stdout, steps.tflint.outputs.stderr) }}
-      #     commenter_exitcode: ${{ steps.tflint.outputs.exitcode }}
+  #     - name: Post TFLint Comment
+  #       if: always()
+  #       uses: GetTerminus/terraform-pr-commenter@dpr-update-commenter
+  #       with:
+  #         commenter_type: tflint
+  #         commenter_input: ${{ steps.tflint-output.outputs.output }}
+  #         commenter_exitcode: ${{ steps.tflint-output.outputs.exitcode }}
 
 
-      - name: Set backend config based on branch
-        id: backend-config
-        run: |
-          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
+  #     # - name: TFLint - Setup
+  #     #   id: tflint
+  #     #   uses: terraform-linters/setup-tflint@v3
+  #     #   with:
+  #     #     tflint_wrapper_enabled: true
+  #     # - name: TFLint - Run
+  #     #   run: |
+  #     #     tflint --version
+  #     #     tflint --init
+  #     #     tflint
+  #     # - name: Post TFLint Comment
+  #     #   if: ${{ always() && (steps.tflint.outcome == 'success' || steps.tflint.outcome == 'failure') }}
+  #     #   uses: GetTerminus/terraform-pr-commenter@dpr-update-commenter
+  #     #   with:
+  #     #     commenter_type: tflint
+  #     #     commenter_input: ${{ format('{0}{1}', steps.tflint.outputs.stdout, steps.tflint.outputs.stderr) }}
+  #     #     commenter_exitcode: ${{ steps.tflint.outputs.exitcode }}
 
-          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-            echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
-            echo "env=prod" >> $GITHUB_OUTPUT
-          else
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
-          fi
-      - name: Terraform Init
-        run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
+
+  #     - name: Set backend config based on branch
+  #       id: backend-config
+  #       run: |
+  #         if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
+
+  #         elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+  #           echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=prod" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
+  #         fi
+  #     - name: Terraform Init
+  #       run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
 
       
 
-      - name: Run tflint and terraform fmt check
-        run: |
-          cd terraform1
-          tflint
-          terraform fmt -check
+  #     - name: Run tflint and terraform fmt check
+  #       run: |
+  #         cd terraform1
+  #         tflint
+  #         terraform fmt -check
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform -chdir=terraform1 validate
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform -chdir=terraform1 validate
 
-      - name: Post TF Validate Comment
-        if: ${{ always() && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure') }}
-        uses: GetTerminus/terraform-pr-commenter@v3
-        with:
-          commenter_type: validate
-          commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
-          commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
+  #     - name: Post TF Validate Comment
+  #       if: ${{ always() && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure') }}
+  #       uses: GetTerminus/terraform-pr-commenter@v3
+  #       with:
+  #         commenter_type: validate
+  #         commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
+  #         commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
          
 
-      # - name: Comment lint/fmt/validate results on PR
-      #   if: failure()
-      #   uses: GetTerminus/terraform-pr-commenter@v3
-      #   env:
-      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     comment: true
+  #     # - name: Comment lint/fmt/validate results on PR
+  #     #   if: failure()
+  #     #   uses: GetTerminus/terraform-pr-commenter@v3
+  #     #   env:
+  #     #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     #   with:
+  #     #     comment: true
 
-  terraform1_security_scan:
-    needs: terraform1_lint
-    runs-on: ubuntu-latest
-    if: needs.filter.outputs.terraform1_changed == 'true'
-    steps:
-      - uses: actions/checkout@v3
+  # terraform1_security_scan:
+  #   needs: terraform1_lint
+  #   runs-on: ubuntu-latest
+  #   if: needs.filter.outputs.terraform1_changed == 'true'
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.12.2
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.12.2
       
-      - name: Set backend config based on branch
-        id: backend-config
-        run: |
-          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
+  #     - name: Set backend config based on branch
+  #       id: backend-config
+  #       run: |
+  #         if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
 
-          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-            echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
-            echo "env=prod" >> $GITHUB_OUTPUT
-          else
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
-          fi
-      - name: Terraform Init
-        run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
+  #         elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+  #           echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=prod" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
+  #         fi
+  #     - name: Terraform Init
+  #       run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
 
       
       
 
-      - name: Run tfsec scan and comment
-        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          tfsec_args: --soft-fail
+  #     - name: Run tfsec scan and comment
+  #       uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         tfsec_args: --soft-fail
 
-  terraform1_plan:
-    needs: [terraform1_lint, terraform1_security_scan]
-    runs-on: ubuntu-latest
-    if: needs.filter.outputs.terraform1_changed == 'true'
-    steps:
-      - uses: actions/checkout@v3
+  # terraform1_plan:
+  #   needs: [terraform1_lint, terraform1_security_scan]
+  #   runs-on: ubuntu-latest
+  #   if: needs.filter.outputs.terraform1_changed == 'true'
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.12.2
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.12.2
 
-      - name: Set backend config based on branch
-        id: backend-config
-        run: |
-          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
+  #     - name: Set backend config based on branch
+  #       id: backend-config
+  #       run: |
+  #         if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
 
-          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-            echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
-            echo "env=prod" >> $GITHUB_OUTPUT
-          else
-            echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
-            echo "env=dev" >> $GITHUB_OUTPUT
-          fi
-      - name: Terraform Init
-        run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
+  #         elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+  #           echo "backend_config=backend-prod.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=prod" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "backend_config=backend-dev.hcl" >> $GITHUB_OUTPUT
+  #           echo "env=dev" >> $GITHUB_OUTPUT
+  #         fi
+  #     - name: Terraform Init
+  #       run: terraform -chdir=terraform1 init  --backend-config=${{ steps.backend-config.outputs.backend_config }} 
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform --chdir=terraform1 plan -lock=false -input=false |& tee tf_plan.txt
-      - uses: GetTerminus/terraform-pr-commenter@v3
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: terraform --chdir=terraform1 plan -lock=false -input=false |& tee tf_plan.txt
+  #     - uses: GetTerminus/terraform-pr-commenter@v3
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
-        with:
-          commenter_type: plan
-          commenter_plan_path: tf_plan.txt
-          commenter_exitcode: ${{ steps.plan.outputs.exit }}
+  #       with:
+  #         commenter_type: plan
+  #         commenter_plan_path: tf_plan.txt
+  #         commenter_exitcode: ${{ steps.plan.outputs.exit }}
